### ISSUE TITLE
Problemas ao executar o exemple.py

### ISSUE THREAD

**Issue by FelipeAmaral13** [pavanad/emec-api#1]
Ao tentar executar o arquivo exemple.py o seguinte erro é retornado.

```
from emec import Institution
ImportError: cannot import name 'Institution' from 'emec'
```
Rodando em ambiente Windows com Python 3.8.3.

**Comment by pavanad** [comment]
Eu criei esse pacote para um projeto já tem alguns anos e pelo que me lembro era em python 2.7 ainda, com relação a importação tente assim:

```python
from emec.emec import Institution
ies = Institution(2132)
ies.parse()

# escreve um arquivo
ies.write_json('emec.json')

# coleta todos os dados
data = ies.get_full_data()
print data
```
Só não tenho certeza se vai coletar todos os dados porque como foi uma raspagem do site do EMEC, se nesses anos alguma coisa foi alterada no layout do site ele não vai coletar corretamente.
